### ISSUE TITLE
Extension: Wrapper around mpbuild which handles micropython git repos

### ISSUE THREAD

**Issue by hmaerki** [mattytrentini/mpbuild#19]
# Use case of octoprobe:

Given a url to a micropython repo, for example `https://github.com/micropython/micropython@v1.24.0-preview`.
Given octoprobe has 2 mcu tentacles connected: rp2, pyboard.

Now octoprobe will call mpbuild for the to 2 mcu tentacles, program the tentacles and run the tests.

# Implementation

* octoprobe has to checkout the git repo. This could be done with this code: https://github.com/octoprobe/octoprobe/blob/main/src/octoprobe/util_cached_git_repo.py.

* Now octoprobe calls mpbuild for rp2, mpbuild will return the pathname to the firmware.
* octoprobe programs the rp2.
* octoprobe runs the tests for the rp2.

The same for the other mcu tentacles.

# Whats next

I plan to implement such a wrapper for octoprobe but I am interested in your opinions.

**Comment by Josverl** [comment]
If you want to do more than just rp2, you  could consider using  mpflash for flashing.
It's been built with that purpose in mind and cause I found myself maintaining the same code in multiple projects.

Chaining or integration with mpbuild makes sense.

**Comment by mattytrentini** [comment]
It seems that this issue is just requesting that `mpbuild` returns the build folder?

And, possibly, can also be used as a module?

If that's correct, I'll close this ticket and create new ones more targeted at those features.

**Comment by hmaerki** [comment]
This feature was added in https://github.com/mattytrentini/mpbuild/pull/54
